### PR TITLE
Sync knative/eventing-sources branch master to openshift/knative-eventing-sources

### PR DESCRIPTION
**Pull request by alanfx**

### CODE REVIEW

**Comment by mgencur** [comment]
@alanfx some of the core image have changed. We'll need to update the Makefile and also the ci-operator config.

**Comment by mgencur** [comment]
Added a commit with re-generated Dockerfiles. And also sent https://github.com/openshift/release/pull/2714 which needs to be integrated first.

**Comment by alanfx** [comment]
OCF Webhook is merging this PR

**Pull request merged**
